name = "SPDEPrecisionMatrices"
uuid = "75a5cc25-472e-45e9-b0be-6a58b1dab74f"
authors = ["Sam Urmy <oceanographerschoice@gmail.com>"]
version = "0.1.0"

[deps]
ConcaveHull = "7d11a335-8259-52c9-8750-e30c45c66484"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TriangleMesh = "e5719326-7e34-5a7d-b19a-3e86f2e9acf7"

[compat]
Interpolations = "0.13"
TriangleMesh = "1.1"
ConcaveHull = "1.1"
